### ISSUE TITLE
not refreshing whatsapp monitoring window

### ISSUE THREAD

**Issue by bikilagalga** [rizwansoaib/whatsapp-monitor#10]
I can get the online tracking history on the terminal but in the whatsapp monitoring window there is no change.

**Comment by rizwansoaib** [comment]
can you please share screenshot

**Comment by rizwansoaib** [comment]
> I can get the online tracking history on the terminal but in the whatsapp monitoring window there is no change.

also mention script_name ans os

**Comment by bikilagalga** [comment]
![IMG_20191227_154730](https://user-images.githubusercontent.com/59268414/71521264-42eece80-28c0-11ea-889b-b3e5e1858de4.jpg)
As you Can See I Can read the conections on the terminal but not on the whatsapp monitor. Im using windows 10.

**Comment by rizwansoaib** [comment]
Please share full terminal i am not getting what you want to say in your terminal writtten 
Madre is en l......

please wait at least 30sec when first time become online 
in window update only when the user changes state self e.g. when goes offline from online or when come online then it will update not always update
