### ISSUE TITLE
Malware found!!

### ISSUE THREAD

**Issue by elanozturk** [rizwansoaib/whatsapp-monitor#11]
Avast warn me about Win64:Malware-gen
![Ekran Alıntısı](https://user-images.githubusercontent.com/22681522/71615239-500e0500-2bc1-11ea-808b-54969e9f7001.JPG)

**Comment by rizwansoaib** [comment]
Source code are open to everyone in Windows folder.

I am surprised to see this and I have no antivirus in my system.

You can generate exe from source code whatsapp-monitor.py

**Comment by rizwansoaib** [comment]
Thank you @elanozturk 

README updated

**Comment by elanozturk** [comment]
Thank you.
