### ISSUE TITLE
Error order in chats

### ISSUE THREAD

**Issue by Contro28** [rizwansoaib/whatsapp-monitor#126]
Suddenly the temporal ordering of the logs of the single contact has changed for some time.
Before it appeared at the bottom but it was in the right order, just go to the last line and you would see the last access and duration.
Now the order is on the contrary and very inconvenient to check.

To make understand:
The entire last part of the log is for October, while the upper part restarts from November 1st.
November 2nd is located just before the beginning of October.
Es.:
1 november
2 november
6 october
7 october
8 october
10 october
ecc.

I also tried to clear the cache (clear chat), and to recreate the contact, but it all returns as described above.

Link shot here: https://imgur.com/HUUxVV5

Thank you very much

**Comment by rizwansoaib** [comment]
#110
