### ISSUE TITLE
sync stops when swapping between wifi and 4G

### ISSUE THREAD

**Issue by MarcKete** [rizwansoaib/whatsapp-monitor#127]
Whenever swapping the phone from wifi to 4G (and vice versa), the desktop app stops logging activities. 

**To Reproduce**
Start the monitoron PC while using phone on wifi. Afterwards change phone to 4G whiel keeping the monitoring open on PC. the monitor no longer notifies/logs any activity from contacts

**Expected behavior**
I would expect that the monitor keeps continiously logging independant from the  type of network you're using

Software
- Win10
- Chrome, but other browser experience same issue
- Desktop version 1.3

**Smartphone 
Android Samsung S8
Android 9

**Comment by rizwansoaib** [comment]
#113
