### ISSUE TITLE
Online feature problem

### ISSUE THREAD

**Issue by don199910** [rizwansoaib/whatsapp-monitor#139]
With the new security feature, the online tracker for people who havent saved your number or texted you ever is now hidden. However, its possible we share the same whatsapp group with said person. Can there be a feature to know when a specific person is online if their online isnt showing?

**Comment by rizwansoaib** [comment]
![Screenshot_2021-12-08-22-47-25-304_com android vending](https://user-images.githubusercontent.com/29729380/145253777-2ebc7c39-288f-484f-8e65-3c4feade97a7.jpg)

![Screenshot_2021-12-08-22-41-47-789_com android vending](https://user-images.githubusercontent.com/29729380/145253787-9113648c-2854-4c1e-b6ee-864f5d2f4516.jpg)


08 Dec 2021 many paid apps also facing issues but some of them also working now .

**Comment by rizwansoaib** [comment]
Whatsapp is changing everyday and update new feature we will try to tweak whatsapp web and let you know.

**Comment by rizwansoaib** [comment]
#128
