### ISSUE TITLE
Question about "my chat" in my contact's WA (his/her phone)

### ISSUE THREAD

**Issue by clecthiago** [rizwansoaib/whatsapp-monitor#146]
Hi, 

I don't know why, but one person of my contact list is not logged anymore to logfile.
The person was my "partner", and i was tracking perfectly, until yesterday.
I suspect the person archived (or even deleted)  my number and chat.

PS: The person doesn't blocks me, because I saw the person online sometime (but I have a problem with browser or extension and forgot to start monitoring ).

Can someone (with 2 numbers or 2 SIMs ) help me testing and report:
 - What happens when my contact **ARCHIVE** the chat ?
 - What happens when my contact **EXCLUDE** the chat ?
 - What happens when my contact **BLOCKS ME** ?

**Comment by malaguer** [comment]
I tried all those cases (including a 4th one: when the contact DELETES you) and WA-Mon can detect online status in everyone of them, except for BLOCKED one.

**Comment by clecthiago** [comment]
Thanks @malaguer for all tests (and the Fourth than I forgot to mention) :+1: 

So in this case, I suppose than my problem maybe is related with issue #145. 
Luckly, In these dats I dont mind a lot about my monitored contact in this month.

@rizwansoaib , can you consider put the info in Readme or Release Notes Please ?
and if you prefer, you can close/resolve this issue too.

Thank you All

**Comment by clecthiago** [comment]
Just informing you guys:

I realized a new thing.
Maybe is obvious for anyeone, but this is new for me.

Yesterday I broke a relationship and decide to block her. 
Maybe I am childish. I was intended to call her out her attention.

So, when I Block someone, i can't monitoring anymore.
