### ISSUE TITLE
WA Monitor - QR Code scan (#144)

### ISSUE THREAD

**Issue by MarcKete** [rizwansoaib/whatsapp-monitor#152]
Hi Rizwan,

Don't know whether you're aware, but guess there's a problem with the QR Code not scanning in the Win version (WA Monitor). The issue seems to be similar to the previously closed #144 .

QR Code scanning works on regular Whatsapp web, but on WA ater scanning the code, it returns error to scan the code again. On the WA Monitor the WA webinterface keeps on displaying the spinning circle.

kr, Marc

**Comment by rizwansoaib** [comment]
I have checked yesterday it was working fine.

**Comment by MarcKete** [comment]
Just tried again, and still same error message : "scan code again" + the infinite loop on WA Monitor. I can send you screencaps with datestamp if you like

**Comment by MarcKete** [comment]
ok, issue solved. I've noticed that in the license windows V 1.3 was displayed. So I checked the program shortcut. For some reason the old shortcut still pointed to a previous installation directory. Redirected the link, and OK now. Sorry for the inconvenience
