### ISSUE TITLE
Monitoring BUG and Debug/Fix + Improvements/Suggestions

### ISSUE THREAD

**Issue by Tarumahr** [rizwansoaib/whatsapp-monitor#154]
PROBLEM #145:
WITH BETA If the main windows are minimized, the monitoring doesn't work at all. Tested more times. No solution for me, right now.
OS: Win 10 Pro 21H2
App: EXE launcher 1.4 (Beta multi-device)

WITH NON BETA DEBUG/FIX: 
#The fix is done with NON-beta device (Beta WON'T WORK with this trick)
OS: Win10Pro x64 21H2
APP: EXE Launcher 1.4

- Set the WA device in a single device mode (old mode, non-beta);
- Start monitoring after setting the contacts to monitor (you have to put a chat in the WA main windows);
- You CAN minimize the monitoring windows;
- You CAN'T minimize the main windows (WA);
- You CAN put the main windows in the background (so you can use other apps, just don't minimize WA main interface);

SUGGESTIONS:
- Let us choose WHO to track, selecting the number or the contact;
- Let us choose if having a MINIMAL AND SIMPLE MONITORING INTERFACE (less performance impact; too heavy right now - especially from to 1.3 to 1.4 update)
- A Good Updated tutorial for "random people" can be useful;
- Simplify how to download the updated .exe file...(actually I have to change page more times and switch website);
- Update pages; Some of them are old and tell ".exe are not supported/developed anymore"

@rizwansoaib   Thanks for your hard work, mate.

**Comment by rizwansoaib** [comment]
1. Let us choose WHO to track, selecting the number or the contact;
Issue already created definitely we will work on next version as feature requests.


2.Let us choose if having a MINIMAL AND SIMPLE MONITORING INTERFACE (less performance impact; too heavy right now - especially from to 1.3 to 1.4 update)
Many people want UI should be more clean and pretty look so RAM usage will be more and GPU also. 
For minimal we need to use chrome extension.

3.A Good Updated tutorial for "random people" can be useful;

I will do that after some stable version.

**Comment by Tarumahr** [comment]
@rizwansoaib 
From RELEASES...here -> https://github.com/rizwansoaib/whatsapp-monitor/releases/tag/dv1.4     NO .exe present (I'm not a developer nor a programmer. 
From here -> https://github.com/rizwansoaib/whatsapp-monitor/tree/master/Windows        Page it's outdated. Delete it? 
To download the .exe I have to go -> https://github.com/rizwansoaib/whatsapp-monitor/tree/master/Desktop%20App

Why can't I simple download .exe from the RELEASES section? Easy...not?
