### ISSUE TITLE
Whatsapp not show online status

### ISSUE THREAD

**Issue by bluej4ker** [rizwansoaib/whatsapp-monitor#158]
Hello,

I used to be able to follow the online status of people I had never contacted before with a different number. Now whatsapp does not send me the online status of the contacts without contacting him. What can I do about this situation?

**Comment by rizwansoaib** [comment]
#128

**Comment by bluej4ker** [comment]
Actually my problem is that whatsapp is not sending me their online and offline status. But after sending any message to the numbers, it starts sending. How do I manage to receive it without sending a message?

**Comment by Stamperx** [comment]
a bit erratic for me too. If I'm in conversation, it is ok but for others who are my contacts it's doesn't always work. By the way, I see whatsapp web is being forced to update along with whatsapp ( I think its to the current beta version). Will this extension still work? Or will you be able to fix it? Thanks in advance for your help.
