### ISSUE TITLE
"You are currently not connected to any networks" when trying to access https://whatsappanalysis.in/online

### ISSUE THREAD

**Issue by cflowers007** [rizwansoaib/whatsapp-monitor#160]
When I try to access my dashboard on Google Chrome, instead of going to the dashboard as usual, the page says "You are currently not connected to any networks."

**To Reproduce**
1. Either click on "Whatsapp Monitor Online History" from the Chrome extension or directly go to https://whatsappanalysis.in/online
2. As soon as I do this, the link opens to a window with the message "You are currently not connected to any networks"

**Expected behavior**
Clicking or following the link should open up the dashboard

**Screenshots**

**Desktop (please complete the following information):**
 - macOS Big Sur Version 11.6.3
 - Chrome Version 99.0.4844.51
 - WhatsApp Web Version: Version 2.2208.7
 - Note that I am NOT in the beta

**Smartphone (please complete the following information):**
 - iPhone 13 Pro
 - OS: 15.3.1
 - WhatsApp iOS App Version: 2.22.3.76

<img width="768" alt="Screen Shot 2022-03-14 at 23 50 17" src="https://user-images.githubusercontent.com/1988858/158274025-b4d292b1-eda4-4fef-8d16-ab19f0c40f0f.png">

**Comment by rizwansoaib** [comment]
Sorry you are facing issue but I am planning to discontinue web services only 3-4% users are using whatsappanalysis web service which is not more than 100 people.

so I didn't renew domain if I will be free with too much time then I try to rewrite web app with NextJs and improve user experience and as well as add some more features.

But I can't promise it will be sure I can try if time permits me currently I am busy with other things so unable to maintain this project.

Thank You

**Comment by rizwansoaib** [comment]
Please download data locally to your system fro. Desktop app or browser extension

**Comment by cflowers007** [comment]
Sorry for the late reply. I understand and really really hope you rewrite it (or keep the old version, it worked/looked great!!). 

Is there any way you can retrieve old data or is this now gone? 

Also, downloading the data in CSV is not working as it should (and is unfortunately a much worse experience). Instead of downloading the online status of the **one** number I track,  it downloads the online status of all contacts I send/receive messages from. This is the case, even if I keep the chat window open on my desktop (Mac) to the number I'm tracking and only respond on my phone.  Let me know if I should open a new issue for this.
