### ISSUE TITLE
whatsapp monitor

### ISSUE THREAD

**Issue by CharlieBrown27** [rizwansoaib/whatsapp-monitor#161]
Hello Rizwansoaib

The big problem are the change that Meta did recently, web version disconect the sesión almost 5 seconds after you left it and work in other thing or windows, can you change that???? if I am on the whatsapp web, the monitor works so well but,  if i left the window, then it  stop monitorin almost instantly because whatsapp disconeted the session.

Regards

**Comment by rizwansoaib** [comment]
#145
