### ISSUE TITLE
online / last seen information disappears in  WhatsApp web, the monitor stops monitoring

### ISSUE THREAD

**Issue by LouisXIVLouis** [rizwansoaib/whatsapp-monitor#162]
Hi. Whatsapp web is not working like it used to even a couple of days ago. 
Normally the online and last seen info is displayed below the contact name, just like in the mobile app.
Now on my browser that information is shown for around 90 seconds or so, then it disappears.
If I move the mouse in the chat part of the browser window, the information comes back and the disappears again 90 seconds later.
While the information is absent, the contact can come online but that is not displayed and the monitor registers nothing new.
My mobile app shows this information continuously for contacts with the privacy setting which allows for sharing of last seen info, obvi. 
I'm using the firefox extension in Firefox on Ubuntu and  Firefox on MacOS. The same behaviour is observed when I use Chrome or Safari on MacOS or the Whatsapp app for MacOS. 

**To Reproduce**
1. Display a chat. Wait 90 seconds
2. Observe the last seen info disappears
3. Move the pointer in the chat pane of the WhatsApp web window
4. Observe the last seen info comes back for 90 seconds, then disappears again

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.10; MacOS 11.6.5
 - Browser Firefox 98.0.2 (MacOS and Ubuntu) with monitor extension v2.7
 - The same behaviour is observed with Chrome 99.0.4844.84 and Safari 15.4

**Comment by rizwansoaib** [comment]
#145
