### ISSUE TITLE
Notify Run not working?

### ISSUE THREAD

**Issue by Stamperx** [rizwansoaib/whatsapp-monitor#164]
**Describe the bug**
Notify run does not seem to be working. Ive tried a new channel but it does not pick up the contact when it comes online .  Whatsapp monitor on whatsapp web shows online status but it does not go to notify run. Could you please take a look? Thanks!

**To Reproduce**

**Expected behavior**
_**notity run should pick up when whatsapp monitor shows online**_

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Browser [e.g. stock browser, safari] mozilla

**Additional context**

**Comment by rizwansoaib** [comment]
notify creator used rate limiting if from one ip used 20 msg in one minute then ip will blocked.

This is one possibility.

For more I need to check I will try and update hete

**Comment by Stamperx** [comment]
please take a look  . Definitely not 20 msg per minute for me  Thanks

**Comment by Stamperx** [comment]
It’s still not working in Mozilla ( haven’t updated to latest version) but seems somewhat functional on chrome. However it seems that once you leave the WhatsApp web page or go onto the app in your phone it can drop and stop monitoring    Could you take a look ? Thanks !

**Comment by rizwansoaib** [comment]
#145

**Comment by meins-rbg** [comment]
Hello,

same problem, online or offline are no longer displayed or documented as soon as the window is minimized.
Or you are not in the same chat.
Same problem is also about a script in the developer tools, with the window open it works if you are in the chat of the contact.


Firefox 98.0.2 
Windows 10 Pro
Version 10.0.19043 Build 19043
Android 11
