### ISSUE TITLE
Only works when the WA Web is active on the screen, does not work otherwise.

### ISSUE THREAD

**Issue by Upanshu13** [rizwansoaib/whatsapp-monitor#170]
**Describe the bug**
Monitoring only works when the WA Web is actively being used if minimised tracking stops, same is the issue with desktop version, rizwan please fix it.

**Comment by rizwansoaib** [comment]
#145

**Comment by Upanshu13** [comment]
> #145

which "dashboard" are we talking about in that, how do i access it?
