### ISSUE TITLE
Extension no longer working: "Phone number shared via url is invalid" error message

### ISSUE THREAD

**Issue by cflowers007** [rizwansoaib/whatsapp-monitor#171]
**Describe the bug**
Yesterday, I updated my iOS app which also updated the web app. Since then, the extension no longer works. 

When trying to track a number as per the usual way that's worked for almost a year, the error message "Phone number shared via url is invalid" pops up

Note that I am not part of the multi-device beta

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur 11.6.5
 - Browser: Chrome
 - Version: Version 101.0.4951.64 (Official Build) (arm64)
   **_- WhatsApp Web version: 2.2216.8_**

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: iOS 15.4.1
 - WhatsApp Version: 22.10.76

**Additional context**
Not part of the multi-device beta
<img width="297" alt="Screen Shot 2022-05-18 at 22 45 39" src="https://user-images.githubusercontent.com/1988858/169153993-b8211311-7049-4d4e-a186-872125acae87.png">

**Comment by rizwansoaib** [comment]
please describe steps to produce this error

**Comment by cflowers007** [comment]
Here's a screencast to show what's going (the error message is at 0:48): https://www.screencast.com/t/EJuPsGhsisPn

Steps: 
1. Click on extension
2. Input number of minutes for CSV autosave (I get the same error message if don't input any minutes)
3. Click on open chat
4. After 45 seconds, the error message pops up

*I also have WAIncognito extension installed but even if I remove this from chrome, I get the error message

**Comment by rizwansoaib** [comment]
When you open extension scroll down to bottom 
Favourite Contacts

remove all contacts which you added in Favourite Contacts.


or just reinstall extension 

I hope it will help .


Thank You

**Comment by cflowers007** [comment]
Thank you!

That worked to get rid of the error message but it's still not tracking online status. 

I just refreshed whatsapp web and saw "Now send and receive messages without keeping your phone online. Use WhatsApp on up to 4 linked devices and 1 phone at the same time," so I think they put me in the multi-user beta

Does the extension not work in this case? Any advice?

<img width="401" alt="Screen Shot 2022-05-20 at 14 30 10" src="https://user-images.githubusercontent.com/1988858/169528507-cfe758b6-ca3c-41fe-af2d-05c47af29ae4.png">

**Comment by cflowers007** [comment]
Actually, I figured out why contacts that were online weren't being shown as online in WA Web. 

(I was the one who opened #145 :) )

**Comment by rizwansoaib** [comment]
@cflowers007 have you tried with pyautogui because i have tested it personally it was working fine?


But for long duration like more than 1hr i did not tested it.

**Comment by rizwansoaib** [comment]
> Actually, I figured out why contacts that were online weren't being shown as online in WA Web.
> 
> If you hide your online status via WA Incognito or the "invisible mode" in WA Web Plus, this prevents you from seeing when a contact is online, as well as their "last seen" time.
> 
> (I was the one who opened #145 :) )

So after off invisible mode are you able to see online activity without pyautogui?

**Comment by GitUserEighty** [comment]
> Actually, I figured out why contacts that were online weren't being shown as online in WA Web.
> 
> If you hide your online status via WA Incognito or the "invisible mode" in WA Web Plus, this prevents you from seeing when a contact is online, as well as their "last seen" time.
> 
> (I was the one who opened #145 :) )

Are you able to see the contacts online . Please let us know the steps .
