### ISSUE TITLE
Not able to monitor with desktop app

### ISSUE THREAD

**Issue by zib8** [rizwansoaib/whatsapp-monitor#175]
**Describe the bug**
First I tried chrome extension but I couldn't make it work. So then I decided to try desktop app. I downloaded it from this link: https://github.com/rizwansoaib/files/raw/master/WhatsApp-Monitor%20Setup%201.4.0.exe

After installation, I logged in. Then I clicked "start monitor". But it is not monitoring any activity. I tried with a friend. I don't see any log. It says "No Online History".

**To Reproduce**
1. Download desktop app.
2. Login to desktop app with qr code.
3. Click one of your contacts.
4. Click "Tools".
5. Click "Start Monitor".

**Expected behavior**
Monitoring should be starting. But nothing happens.

**Desktop (please complete the following information):**
 - OS: Win 10

**Comment by rizwansoaib** [comment]
#145
