### ISSUE TITLE
WhatsApp monitor not working after latest update

### ISSUE THREAD

**Issue by Stamperx** [rizwansoaib/whatsapp-monitor#176]
**Describe the bug**
WhatsApp monitor app starts and seem to work but once away even though the screen is open and maximise it stops picking up when the contact comes online. 
I tested with a spare number and the account used in what’s app monitor does not even appear online after the initial bit when it was started. 
I tried sending a test message and although it was delivered ( 2 ticks) but not read even though the WhatsApp monitor is open and maximised. It’s just seem to be frozen and inactive. The message is not read and even when I try to click on the contact ( which is me) it does no update

If I restart using WhatsApp monitor actively on desktop again ( like I message the contact )  it restarts 

so what happens is that the monitor starts and after some inactivity seems to stop even though I’ve left it on and maximised. And it will then miss when the contact comes online. 
 If I restart using WhatsApp monitor actively on desktop again ( like I message the contact )  it restarts  
Can you see if you could debug this? If any one has similar issues or knows a workaround can you let me know too ?

Thanks so much ! 

**To Reproduce**
1. Go to '.WhatsApp monitor app..'
2. Click on '..start monitor, click on contact to monitor ..'

**Expected behavior**
Monitors when contact online even when away from desktop , not only when I’m using the desktop WhatsApp or actually WhatsApp Imsg the contact 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 10 
 - Browser [e.g. chrome, safari] WhatsApp monitor [app
 
](url)
**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone 7 and 13 
 - OS: [e.g. iOS 15.5

**Comment by Stamperx** [comment]
Just an update :  I tried using a mouse juggler and that helps to keep the chat active. Otherwise once the chat becomes ‘inactive’ the monitor may not pick up the activity. But not sure if this works for non contacts ( those you don’t have a conversation with)   This method with the jiggler only works for the active chats.

**Comment by rizwansoaib** [comment]
#145

**Comment by pleistoneun** [comment]
I am working with the Chrome Extension.
The problem is, that the value "__x_isOnline" isnt **true** or **false**; this value looks like this -> "{sentinel: 'DEFAULT VALUE PLACEHOLDER'}". So you cannot grab the value.

**Comment by pleistoneun** [comment]
Yes, thats correct, but how can i detect if a contact is online?

**Comment by rizwansoaib** [comment]
Yes

**Comment by pleistoneun** [comment]
I will try i immediately...
Thanks!!!

**Comment by Stamperx** [comment]
The mouse jiggler ( sorry i typo earlier ) that issue for windows is this : https://www.screensaversplanet.com/software/mouse-jiggler-651/

im sure there are other links for download

**Comment by meins-rbg** [comment]
Please, can anyone explain it for "Litlle less knowers" what i have to do and where?
Thanks
