### ISSUE TITLE
Unable to use old Notification Key with v2.8 - 

### ISSUE THREAD

**Issue by cflowers007** [rizwansoaib/whatsapp-monitor#179]
**Describe the bug**
In the new version of the chrome extension, I'm unable to use the old Notification Key as there's no empty box. Instead, it says "Notification Key QR undefined" (with a broken image icon)

**To Reproduce**
1. Click on extension icon in chrome bar
2. Instead of blank box to enter existing Notification Key, it says "Notification Key QR undefined" (with a broken image icon)
3. Clicking "undefined" leads to chrome-extension://emkoflhmeegjlabodebpfbkeicjppebi/undefined
4. I removed and reinstalled the extension but am still seeing the same thing

**Screenshots**
<img width="402" alt="Screen Shot 2022-07-06 at 09 57 58" src="https://user-images.githubusercontent.com/1988858/177500831-ceafb78a-e5d6-45dd-a9d4-817d4ea59258.png">

**Desktop (please complete the following information):**
 - OS: macOS Big Sur
 - Browser: Chrome
 - Version: 103.0.5060.114

**Comment by cflowers007** [comment]
I can't use the old key I've been using for over a year?

**Comment by rizwansoaib** [comment]
No issue you can generate new and use new one

**Comment by rizwansoaib** [comment]
For old key i have removed now you can generate from click on button

**Comment by cflowers007** [comment]
> For old key i have removed now you can generate from click on button

I don't understand, sorry. You just mean that for v2.8, we need to generate a new key and if we want to use the old one, we need to use v2.7 correct? (sorry for opening two of the same issues, not sure how that happened!)
