### ISSUE TITLE
WAPI.createGroup error

### ISSUE THREAD

**Issue by mikelustosa** [rizwansoaib/whatsapp-monitor#181]
**WAPI.createGroup not work**

**To Reproduce:**
1. Go to WAPI.createGroup("new group", "558199301443@c.us");

**Error message:**
Cannot read properties of undefined (reading 'map')

**Comment by rizwansoaib** [comment]
How this is related to online activity repo is focusing more on online monitor.



You can check other repo WhatsApp web revenge or Bailey for this
