### ISSUE TITLE
Wrong sorting order on the website and charts are not working due to that

### ISSUE THREAD

**Issue by fabrus-pl** [rizwansoaib/whatsapp-monitor#182]
I started using logging to wpmonitor.tech again :) Thanks for bringing back that featutre.
However after two days of using I noticed the following:
- Charts worked fine for the first day only (I will explain most likely reason of that issue below)
- Calls are sorted in wrong order - the AM hours are mixed with PM hours so I got mixed data like following:
07 Jul, 04:07:20 PM
07 Jul, 06:23:41 AM
07 Jul, 06:36:18 PM

For me - sorting looks like it is done as string alphabetically, so in that case 07 Jul, 06:23:41 AM gets between 07 Jul, 04:07:20 PM and 07 Jul, 06:36:18 PM.

- This most likely has broken the charts, because I started to gather data in PM hours and it worked until next day. 

Maybe if the 24-hour notation would be used, the sorting would have been done properly

**Comment by rizwansoaib** [comment]
The issue is fixed.

Please let me know if any bugs or user experience need to upgrade.

**Comment by fabrus-pl** [comment]
It works, both sorting and the charts. Thanks!
