### ISSUE TITLE
After last Whatsapp Web Update, the WOL and CSV downloadbuttons in UI disappeared

### ISSUE THREAD

**Issue by Box333** [rizwansoaib/whatsapp-monitor#189]
After last Whatsapp Web Update, the WOL and CSV Download Buttons in UI disappeared.

Tested with Firefox Extension v2.8  on Firefox v104.0b7 (64-Bit) and 104.0b9 (64-Bit)

**Comment by GitUserEighty** [comment]
Even in chrome the same issue 

Uncaught TypeError: Cannot read properties of null (reading 'appendChild')
    at online.js:207:41
(anonymous) @ online.js:207

**Comment by rizwansoaib** [comment]
Please update here everyone if anyone facing same issues i did not checked yet but for some person working fine.



I need to know WhatsApp version and browser version.

**Comment by rizwansoaib** [comment]
> Even in chrome the same issue
> 
> Uncaught TypeError: Cannot read properties of null (reading 'appendChild') at online.js:207:41 (anonymous) @ online.js:207

What is your chrome version and WhatsApp version?

**Comment by Azrael1980** [comment]
> What is your chrome version and WhatsApp version?

Версия 104.0.5112.81 (Официальная сборка), (64 бит) Chrome : Версия 2.2230.10 Whatsapp

**Comment by LouisXIVLouis** [comment]
Same issue here. Using extension v2.8 on

Chromium 2.0.4515.98 (Official Build) Built on Raspbian , running on Raspbian 10 (32-bit)
and Firefox 103.0.2 (64-bit) on Mac Big Sur

Linked to whatsapp v22.16.77 on iphone

Online/offline data is visible on wpmonitor.tech but as stated by the OP, the csv download button is not visible in the browser.

In addition, the online sound alert does not seem to sound; but the offline-red/online-green status indication is applied to the contact name.

**Comment by rizwansoaib** [comment]
> Same issue here. Using extension v2.8 on
> 
> Chromium 2.0.4515.98 (Official Build) Built on Raspbian , running on Raspbian 10 (32-bit) and Firefox 103.0.2 (64-bit) on Mac Big Sur
> 
> Linked to whatsapp v22.16.77 on iphone
> 
> Online/offline data is visible on wpmonitor.tech but as stated by the OP, the csv download button is not visible in the browser.
> 
> In addition, the online sound alert does not seem to sound; but the offline-red/online-green status indication is applied to the contact name.

Thanks @LouisXIVLouis for this info

**Comment by rizwansoaib** [comment]
It's from WhatsApp end they change in html okay i will try to fix.

**Comment by rizwansoaib** [comment]
issue got fixed and whatsapp web team changed their UI html xpath so it was failing.

**Comment by rizwansoaib** [comment]
Firefox Extension will be listed soon and updated but for chrome google review, it will take more than 72hr.

**Comment by rizwansoaib** [comment]
Please let me know any improvement or feature request I will submit it for chrome after 2 days.

**Comment by rizwansoaib** [comment]
> Even in chrome the same issue
> 
> Uncaught TypeError: Cannot read properties of null (reading 'appendChild') at online.js:207:41 (anonymous) @ online.js:207

Thank You @GitUserEighty for posting error messages its help me for quick debug and fix this issue

**Comment by Box333** [comment]
> Please let me know any improvement or feature request I will submit it for chrome after 2 days.

could you make the log vertically scrollable?
you could to so, by embedding the html <table> tag into a <div> and set the css property to overflow: auto

**Comment by Azrael1980** [comment]
Pls make "Last Seen: 13 Aug, 12:57 AM" - option in 24h format? And add button to delete logs for people or period.

**Comment by LouisXIVLouis** [comment]
> Firefox Extension will be listed soon and updated but for chrome google review, it will take more than 72hr.

I confirm extension v2.9 for Firefox (I'm using 103.0.2) works for me as it did previously.

Thank you!
