### ISSUE TITLE
wpmonitor.tech is down :(

### ISSUE THREAD

**Issue by fabrus-pl** [rizwansoaib/whatsapp-monitor#191]
Website at womonitor.tech is down for few days now.
Is this due to some maintenance or is there any other reason for that?

**Comment by rizwansoaib** [comment]
https://wpmonitor.tech

There are multiple reason -
1. Currently only few are active users for web portal around not more than 100
2. Domain will expire in late 2022
3. Server was running AWS Free tier so plan were also expired.
4. Total users decreases as after whatsapp update need to active at chat window and concurrency will hamper if we download jiggler or auto move mouse.
5. I am planning to discontinue project in early 2023 so this project will no longer support for any further updates and maintenance.


These are main reason so i did not bought new domain and server to update web portal.


Thank You

**Comment by Stamperx** [comment]
😩 I really liked this. Will you maintain and update the desktop monitor?

**Comment by rizwansoaib** [comment]
But even desktop monitor we need to active on chat window if we use any external mouse simulator then we can not perform other task how you are handling.

**Comment by rizwansoaib** [comment]
I tried to implement inbuilt features for auto moving mouse within chat window in desktop app but failed

**Comment by Stamperx** [comment]
Thank you for having done this. I hope you will revive it again in future. You did something many failed to despite all the hurdles. Good luck in your other projects in the mean time.

**Comment by rizwansoaib** [comment]
add on v3 updated with new domain
