### ISSUE TITLE
wpmonitor.online not working 

### ISSUE THREAD

**Issue by cflowers007** [rizwansoaib/whatsapp-monitor#204]
**Describe the bug**
When I try to load https://wpmonitor.online/, I either get a screen saying that I'm not online, or I get a screen saying "This site can’t be reachedwpmonitor.online took too long to respond."

I've tried loading the site on 2 computers and my ipad, but each time it fails to load

**Screenshots**
<img width="404" alt="Screen Shot 2023-02-22 at 20 00 58" src="https://user-images.githubusercontent.com/1988858/220732087-bb59072d-5ad8-474d-bbe6-567ba84f2ccc.png">
<img width="411" alt="Screen Shot 2023-02-22 at 19 58 31" src="https://user-images.githubusercontent.com/1988858/220732318-c576b769-6f75-4458-987b-f28096af209c.png">

Chrome Version 109.0.5414.119

**Comment by rizwansoaib** [comment]
Wpmonitor it's hosted on AWS server cost I didn't paid so it's offline

**Comment by rizwansoaib** [comment]
@cflowers007 please can you confirm extension is working?

I will try restart server with another free tier AWS account soon but atleast it will take 15 days currently I have no system or laptop sorry for inconvenience 😭
