### ISSUE TITLE
https://wpmonitor.online/ not work again

### ISSUE THREAD

**Issue by Azrael1980** [rizwansoaib/whatsapp-monitor#210]
https://wpmonitor.online/ 
Your Connection is Offline.

**Comment by rizwansoaib** [comment]
Server is running on AWS Free Tier I think free trial period is over I will try to fix ASAP but there is no guarantee that problem will be fix.

**Comment by rizwansoaib** [comment]
A new Free Tier AWS instance initiated

**Comment by rizwansoaib** [comment]
@Azrael1980 Please Close issue its fixed now

**Comment by Azrael1980** [comment]
Thx

**Comment by Azrael1980** [comment]
Your Connection is Offline.
Please check your Wifi Connection.

**Comment by rizwansoaib** [comment]
Will check and update here

**Comment by rizwansoaib** [comment]
Please check again and revert back I think someone did Ddos purposely

**Comment by Azrael1980** [comment]
All work bro, your application is the best there is for whatsapp, please don’t give it up.
