### ISSUE TITLE
Firefox and Chrome browser extension is not working / logging contact online status

### ISSUE THREAD

**Issue by Froguser1** [rizwansoaib/whatsapp-monitor#213]
Firefox or Chrome Browser extension of Whatsapp-monitor is not working / logging contact online status since approx. 3 weeks. 

**To Reproduce**
1.	Open Firefox or Chrome 
2.	Go to https://web.whatsapp.com/ 
3.	Login via QR-Code
4.	Search for contact you want to check
5.	Open Firefox or Chrome Extension
6.	Type into Autosave 1 for 1 minute 
7.	Type in telephone number of contact 
8.	Click okay 
9.	Open my Mouse or other Jiggler program 

**Expected behavior**
Notification when contact is online. Autosave and download of excel with online time stamp 

**observed behavior**
Firefox or Chrome Browser extension of Whatsapp-monitor is not working anymore. No notification when contact is online  although online status still appears in Whatsapp App on smartphone or in web.whatsapp.com below contact name. Downloaded excel file is empty.   

**Desktop (please complete the following information):**
•	macOS: 14.4.1 or Windows 10
•	Browser [Firefox 125.0.2; Chrome 124.0.6367.91]
•	Whatsapp-monitor 3.1
•	Whatsapp version on iphone 2.24.8.83

**Comment by Froguser1** [comment]
For Chrome browser extension of whatsapp-monitor 3.2 I can confirm the bugfix.  Firefox browser extension of whatsapp-monitor 3.2 is still **not** working.

**Comment by rizwansoaib** [comment]
Yes I have not tested Firefox 3.2 only based on my assumption I have tried
to fix reason is manifest V3 for chrome and manifest V2 for Firefox.


There should be way to run chrome extension on Firefox so I didn't took
testing for Firefox


I will try to fix in upcoming version.
