### ISSUE TITLE
i have tested with pyautogui its working you can move mouse with script.

### ISSUE THREAD

**Issue by 2267110696** [rizwansoaib/whatsapp-monitor#216]
i have tested with pyautogui its working you can move mouse with script. 

`      import pyautogui as pg `
        `while 1:`
            `    pg.moveTo(1500, 350, duration = 1)`
            `    pg.moveTo(1500, 300, duration = 1)`

_Originally posted by @rizwansoaib in https://github.com/rizwansoaib/whatsapp-monitor/issues/145#issuecomment-1036230160_

**Comment by 2267110696** [comment]
#- [ ] - الصفحة

**Comment by rizwansoaib** [comment]
ما الذي تريد قوله يرجى ذكره وكيف يمكنني مساعدتك فيما يتعلق بهذه المشكلة

**Comment by rizwansoaib** [comment]
Anyone can also buy usb mouse jiggler (cost 5$) to move mouse from online store or nearby shop
