### ISSUE TITLE
https://wpmonitor.online/

### ISSUE THREAD

**Issue by Azrael1980** [rizwansoaib/whatsapp-monitor#218]
Not work again) Fix pls!)))

**Comment by rizwansoaib** [comment]
fixed but domain will expire 1 December 2024

**Comment by rizwansoaib** [comment]
![main_icon_new2](https://github.com/user-attachments/assets/a57849a2-73e4-4f0c-b295-38b5e49e0ca5)

**Comment by rizwansoaib** [comment]
New Domain-

https://trackwapp.online/

**Comment by Azrael1980** [comment]
![изображение](https://github.com/user-attachments/assets/ca730c1c-ba36-4a8c-999d-95dcd77f9ff6)

Access blocked: This application has sent an invalid request.

**Comment by rizwansoaib** [comment]
Yes it's currently blocked reason is extension is not updated on chrome web store once version 3.3 will published then I will enable trackwapp.online Google login

**Comment by rizwansoaib** [comment]
Fixed
