### ISSUE TITLE
the interface buttons have moved to the side

### ISSUE THREAD

**Issue by Azrael1980** [rizwansoaib/whatsapp-monitor#223]
Win 10 Chrome browser

![изображение](https://github.com/user-attachments/assets/8fdcf615-e7bc-4311-8251-83e9b7b2a2c7)

**Comment by rizwansoaib** [comment]
@Azrael1980 please let me know once you get updates latest version and this issue is resolved or not yet

**Comment by Azrael1980** [comment]
> @Azrael1980 please let me know once you get updates latest version and this issue is resolved or not yet

not work( no icons, no writing logs to site

**Comment by Azrael1980** [comment]
Uncaught TypeError: Cannot read properties of null (reading 'parentElement')



var nno=""
var nkey;
chrome.storage.local.get('nno', function (myresult) {
        nno = myresult.nno;
        console.log("nno val in online.js",nno);
        if(nno==2){

  var mnkey=""
  chrome.storage.local.get('mnkey', function (result2) {
          mnkey = result2.mnkey;
          console.log("mnkey val from online.js",mnkey,typeof(mnkey))

          if(mnkey != "undefined"){
            alert("Subcribe any Device for Notification\n"+mnkey)
            nkey=mnkey;
          }
          
            
        });
        
        
        }
                 
    }); 


console.log("nno val from online.js",nno);


pso=""
chrome.storage.local.get('pso', function (result3) {
        pso = result3.pso;

        
            
    });


    console.log("pso val from online.js",pso);


        
        

            
   

  


   




function onotif(user) {
   if(nkey==null||nkey==undefined||nkey==""||nkey=="undefined")
    return
  else{
        var xhr = new XMLHttpRequest();
    xhr.open("POST", nkey,true);
    xhr.send("📱WhatsApp Monitor: "+user+" is Online")

  }

}




function save(user,t1,t2,t){
  var d   = new Date();
  var curd=d.toLocaleDateString("en-GB").split(' ')[0]
  user=user.replace(/[^a-zA-Z0-9]/g, "")
  curd=curd.replace(/[^a-zA-Z0-9]/g, "")

  const surl='https://wpmonitor.online/save/'+user+'/'+curd+'/'+t1+'/'+t2+'/'+t
  var xhr = new XMLHttpRequest();
   xhr.open("GET",surl);
  xhr.send()
  
}







function playsound()
{

let url = chrome.runtime.getURL('open.mp3')
                  let a = new Audio(url)
                  a.play()

}


setInterval(function(){
  try{
    olb=document.querySelector('#online_list_btn').innerText
    if(olb=='true' && pso=='3')
    {
      
      playsound();
    }
    prev=document.querySelectorAll('#userbtn')[0].innerHTML
    if(prev!='null'&&pso=='1')
    {
      playsound();
    }

  }
catch(err){}


try{
  olb=document.querySelector('#online_list_btn').innerText
  if(olb=='true' && pso=='3')
    {
      

      playsound();
    }

  user=document.querySelectorAll('#contactbtn')[0].innerHTML;
  if(user!='null')
    onotif(user);
}
catch(err){}
   


},2200)


















function dcsv2() {
   console.log("Downloading History as CSV File")
    var rows = document.body.querySelectorAll(' table' + ' tr');
    var csv = [];
    for (var i = 0; i < rows.length; i++) {
        var row = [], cols = rows[i].querySelectorAll('td, th');
        for (var j = 0; j < cols.length; j++) {
            var data = cols[j].innerText.replace(/(\r\n|\n|\r)/gm, '').replace(/(\s\s)/gm, ' ')
            row.push('"' + data + '"');
        }
        csv.push(row.join(';'));
    }
    var csv_string = csv.join('\n');

   
    var filename = `whatsapp-monitor_${new Date().toISOString().split('T')[0]}&&${new Date().toLocaleTimeString()}.csv`;
    var link = document.createElement('a');
    link.style.display = 'none';
    link.setAttribute('target', '_blank');
    link.setAttribute('href', 'data:text/csv;charset=utf-8,' + encodeURIComponent(csv_string));
    link.setAttribute('download', filename);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

   

     /*

  console.log(csv,csv_string);
    // Save the CSV file.
var blob = new Blob([csv], {type: 'text/csv'});
var url = window.URL.createObjectURL(blob);
var link = document.createElement('a');
console.log(link,url);
link.href = url;
link.download = 'table.csv';
document.body.appendChild(link);
link.click();
document.body.removeChild(link); 

 */


}







chrome.storage.local.get('save_interval', function (result4) {
        save_interval = parseInt(result4.save_interval);
        if(save_interval>=1)
        setInterval(dcsv2,save_interval*60000);

        
            
    });








function isElementPresentById(id) {
    return document.getElementById(id) !== null;
}




function exec_after_delay(){

    const element_present =document.querySelector('div[aria-label="Status"]').parentElement.parentElement;
    if(element_present && !(isElementPresentById('download')))
    {



        var elementHeight = "30px";

        var btn = document.createElement("BUTTON");
        var btnImage = document.createElement("IMG");


        btnImage.src = "https://raw.githubusercontent.com/rizwansoaib/whatsapp-monitor/master/Chrome-Extension/WhatsApp%20Monitor/images/icons/csv_download.jpg";

        btnImage.style.height = elementHeight;
        btn.appendChild(btnImage);
        btn.id="download";
        element_present.appendChild(btn);


        /*
        var img=document.createElement("IMG");
        img.id="download"
        img.src="https://raw.githubusercontent.com/rizwansoaib/whatsapp-monitor/master/Chrome-Extension/WhatsApp%20Monitor/images/icons/csv_download.jpg"
        document.querySelector("#side > header").appendChild(img);
        */

        var img=document.createElement("IMG");
        img.src="https://raw.githubusercontent.com/rizwansoaib/whatsapp-monitor/master/Chrome-Extension/WhatsApp%20Monitor/images/icons/icon_gray.png"
        img.style.height = elementHeight;
        img.addEventListener("click", function() {
            chrome.runtime.sendMessage({ action: "open_popup" });
        });
        element_present.appendChild(img);



        console.log('background online.js loaded successfully');



        document.getElementById('download').addEventListener('click', dcsv2);

    }

    else{
        setTimeout(exec_after_delay,60000);
    }




}

setTimeout(exec_after_delay,20000);










var numarray=[]
chrome.storage.sync.get('numarray', function (data) {
        numarray = data.numarray;
        if(numarray)
        {

          //console.log('start',numarray);





        numarray.forEach(function(obj, index) {
          setTimeout(function(){
            openChat(obj)
          }, 5000 * (index + 1));
      });

        }

            
    });







    var openChat = phone => {

     // console.log('opening chat...',phone);
      var link = document.createElement("a");
      link.setAttribute("href", `whatsapp://send?phone=${phone}`);
      document.body.append(link);
      link.click();
      document.body.removeChild(link);
    };



/*
chrome.tabs.query({active: true, currentWindow: true}).then(([tab]) => {
    chrome.scripting.executeScript(
        {
            target: {tabId: tab.id},
            files: ['websocket.js'],
            // function: () => {}, // files or function, both do not work.
        })
})


chrome.tabs.query({active: true, currentWindow: true}).then(([tab]) => {
    chrome.scripting.executeScript(
        {
            target: {tabId: tab.id},
            files: ['protobuf.js'],
            // function: () => {}, // files or function, both do not work.
        })
})




chrome.tabs.query({active: true, currentWindow: true}).then(([tab]) => {
    chrome.scripting.executeScript(
        {
            target: {tabId: tab.id},
            files: ['main.js'],
            // function: () => {}, // files or function, both do not work.
        })
})


  */

**Comment by rizwansoaib** [comment]
> > @Azrael1980 please let me know once you get updates latest version and this issue is resolved or not yet
> 
> not work( no icons, no writing logs to site
> 
> 3.2 version, not log to site too (((

I have updated in version 3.3 soon after publish by Google in chrome webstore it will update extension automatically

**Comment by rizwansoaib** [comment]
Temporary solution to use new version 3.3 


https://github.com/rizwansoaib/whatsapp-monitor/tree/master/Chrome-Extension

Features -
1.Now no need to open extension everytime when you open whatsapp it will start automatically if user is logged in WhatsApp Web 



2. No need to move mouse only should be open whatsapp web main screen all time 


Let me know if anyone facing issue unfortunately I didn't tested it more so may be face issue on based on os, chrome version just type your issue here we will try to fix those issues in future updates

**Comment by Azrael1980** [comment]
3.2 works well, but the buttons are on the side. Which doesn't bother me.
3.3 Still doesn't work, writes errors

**Comment by rizwansoaib** [comment]
> 3.2 works well, but the buttons are on the side. Which doesn't bother me. 3.3 Still doesn't work, writes errors

How you are able to use 3.3 its not published on Chrome web store?


Have you tried from release section zip file?

**Comment by rizwansoaib** [comment]
Are you using Whatsapp business? 

I have tested the issue is for different version have different UI on whatsapp web in my Whatsapp there is sidebar on whatsapp web for chat,status, setting,profile, meta ai chat 



I think in your whatsapp web there is no sidebar

**Comment by Azrael1980** [comment]
> > 3.2 работает хорошо, но кнопки сбоку. Что меня не беспокоит. 3.3 Все равно не работает, пишет ошибки
> 
> Как вы можете использовать версию 3.3, которая не опубликована в интернет-магазине Chrome?
> 
> Вы пробовали из zip-файла раздела выпуска?

YES

**Comment by rizwansoaib** [comment]
![Screenshot_2024-11-04-13-50-53-52_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/8b13dd7a-bdfc-4bb3-aa27-8873b6160570)


Whatsapp Web SideBar

**Comment by Azrael1980** [comment]
I use a regular WhatsApp, you can see the sidebar in the picture. This works with version 3.2
On version 3.3 the sidebar is not visible.

![изображение](https://github.com/user-attachments/assets/73e487fc-5d06-41a2-ad78-69ba6c5f66c6)

**Comment by Azrael1980** [comment]
![изображение](https://github.com/user-attachments/assets/6dc4b0cd-a433-4967-b732-af94246b0248)
3.3 error

**Comment by rizwansoaib** [comment]
> ![изображение](https://private-user-images.githubusercontent.com/29340110/382687234-6dc4b0cd-a433-4967-b732-af94246b0248.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MDg5OTcsIm5iZiI6MTczMDcwODY5NywicGF0aCI6Ii8yOTM0MDExMC8zODI2ODcyMzQtNmRjNGIwY2QtYTQzMy00OTY3LWI3MzItYWY5NDI0NmIwMjQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDA4MjQ1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5ODUzNzczOGY1M2U5ZjlkMTEyOWExMWRjZDc2ODc4OGUxODdkZjkxMzFjZGNlYmJkYzI0YjIzOGQ1OGE0OWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uhqM-GLTC1GRuDgGj50WpGi_7G_VJRULH_3D-bCu2-c) 3.3 error

Click on next parent element error

**Comment by Azrael1980** [comment]
> > ![изображение](https://private-user-images.githubusercontent.com/29340110/382687234-6dc4b0cd-a433-4967-b732-af94246b0248.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MDg5OTcsIm5iZiI6MTczMDcwODY5NywicGF0aCI6Ii8yOTM0MDExMC8zODI2ODcyMzQtNmRjNGIwY2QtYTQzMy00OTY3LWI3MzItYWY5NDI0NmIwMjQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDA4MjQ1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5ODUzNzczOGY1M2U5ZjlkMTEyOWExMWRjZDc2ODc4OGUxODdkZjkxMzFjZGNlYmJkYzI0YjIzOGQ1OGE0OWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uhqM-GLTC1GRuDgGj50WpGi_7G_VJRULH_3D-bCu2-c) 3.3 error
> 
> Click on next parent element error

![изображение](https://github.com/user-attachments/assets/3c20ce95-f96a-4287-b4bf-d2cac30122e4)

**Comment by rizwansoaib** [comment]
I will try to fix in next updates this error 

Within 5 days

**Comment by Azrael1980** [comment]
Thanks

**Comment by rizwansoaib** [comment]
> Thanks

Please update your whatsapp in smartphone 


Maybe I am on latest version of Whatsapp so sidebar is showing

**Comment by Azrael1980** [comment]
![photo_2024-11-04_11-45-16](https://github.com/user-attachments/assets/c27db97c-397e-4e4e-a034-b1596a98c4c4)
Latest version for Russia)

**Comment by rizwansoaib** [comment]
Ok i got that I have beta 

![Screenshot_2024-11-04-14-43-31-01_6012fa4d4ddec268fc5c7112cbb265e7](https://github.com/user-attachments/assets/4f608ce3-8b53-4d22-88d5-a576e2025a5b)



Now I will try to fix bug based on your whatsapp version 


Thank you for sending screenshot

**Comment by rizwansoaib** [comment]
[chromev3.3_new.zip](https://github.com/user-attachments/files/17628927/chromev3.3_new.zip)


This is alpha development version 

@Azrael1980 please can you check by using extension in developer mode

**Comment by rizwansoaib** [comment]
Even don't need to enable extension now from version 3.3 no need to open extension popup every time or click ok



Only need to open WhatsApp web and open contact chat ( or add contacts in favourite to open chat automatically)

**Comment by rizwansoaib** [comment]
Please check this also just close browser, open browser, open Whatsapp web 



Once Whatsapp web will open automatically monitoring will start

**Comment by Azrael1980** [comment]
No. If I don't launch the application, it goes to WhatsApp error

**Comment by Azrael1980** [comment]
![изображение](https://github.com/user-attachments/assets/32fa7d5c-8270-41c4-baec-2fd97f7ff2a1)

![изображение](https://github.com/user-attachments/assets/c30de8ae-0852-442a-84b9-6adfe39c4c96)

**Comment by rizwansoaib** [comment]
Refresh url at whatsapp web opened already 


Wait for 30 sec if (icon of CSV downloader, Extension icon) in chat header its mean its working 


Please try above steps 



If not working this send me console error( Ctrl+shift+c then console tab) or browser extension error ( chrome://extensions)

**Comment by Azrael1980** [comment]
[web.whatsapp.com-1730805808109.log](https://github.com/user-attachments/files/17631634/web.whatsapp.com-1730805808109.log)


I clear phone numbers

**Comment by rizwansoaib** [comment]
From log i think there should be no issue 



@Azrael1980 does after refresh Whatsapp web after 30 sec extension icon and CSV downloader appeared in chat header ?

**Comment by Azrael1980** [comment]
> From log i think there should be no issue
> 
> @Azrael1980 does after refresh Whatsapp web after 30 sec extension icon and CSV downloader appeared in chat header ?

No

**Comment by rizwansoaib** [comment]
Ok 

I need to test it more on different devices,version,os etc. 



I will update here if I found any bug or feature not working

**Comment by Azrael1980** [comment]
> [chromev3.3_new.zip ](https://github.com/user-attachments/files/17677708/chromev3.3_new.zip)

Works well in the following sequence:
Refresh the tab - turn on the add-on. No need to move the mouse, there are no icons.
Doesn't work if the add-on is enabled - refresh the tab or open the browser. It seems to start, but there is no time stamp under the name (I'll attach a picture) And the pop-up does not appear when the user is online.

![изображение](https://github.com/user-attachments/assets/e8fb90a0-8af2-432f-8f1e-8d2f5ffd0dac)

**Comment by rizwansoaib** [comment]
Final version released 

https://github.com/rizwansoaib/whatsapp-monitor/releases

in Windows, no Notification is showing but i have added Sound Alert please let me know sound Alert is working or not 
I have tested on Mac its works well both notifications and sound.

**Comment by Azrael1980** [comment]
The sound works. 
But other problems remained the same.

**Comment by rizwansoaib** [comment]
Please list other problems 


Will try to fix in upcoming version
