### ISSUE TITLE
Date Time Stamp

### ISSUE THREAD

**Issue by peskywinnets** [rizwansoaib/whatsapp-monitor#24]
Hi,

thanks for this...I've just downloaded the Chrome Extension & it seems to be working fine.

Can I ask for a simple mod please?

Either a datetimestamp e.g. 02/04/2020 22:30:01 ...or if not possible at least a date stamp (for the short time I've been running it only seems to have the time (no date) 

P.S. I see that the downloaded file has a date embedded in its filename...but what if the monitoring timespan goes across several days?

**Comment by rizwansoaib** [comment]
Depend upon people responses star , fork and discussion.
Will add this feature

**Comment by peskywinnets** [comment]
The reason I ask, is because if the file contents are imported into into a database ...without a date embedded in the file online/offline content, the data content can't be imported for several days worth (as it's not clear which actual date the online/offline times relate to)

Also, when I click 'Download History'...I occasionally get a 'permission denied' error (could it be because the use was online at the time?)
