### ISSUE TITLE
FR

### ISSUE THREAD

**Issue by roelandjansen** [rizwansoaib/whatsapp-monitor#29]
hi, 

nice tool; I use this for checking the (number of and time of) messages sent from a monitoring system when I am asleep.
Wondering if you could add the date before the time as well, as yyyymmdd

**Comment by Baricanac** [comment]
I concur, something like the following table format in a CSV file would be nice;

1. Date (ddmmyyyy) 
2. Time online
3. Time offline
4. Duration

**Comment by rizwansoaib** [comment]
Thanks we will try adding in Next improved version soon....
