### ISSUE TITLE
SessionNotCreatedException on webdriver.Firefox(options=options)

### ISSUE THREAD

**Issue by BuileaTM** [rizwansoaib/whatsapp-monitor#3]
Hi there,

Great tool! But when i run it in Docker it keeps throwing this error:

> sudo` docker run whatsapp-monitor
> Please Wait Starting whatsapp-monitor
> Traceback (most recent call last):
>   File "./monitor+log.py", line 21, in <module>
>     driver = webdriver.Firefox(options=options)
>   File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/firefox/webdriver.py", line 170, in __init__
>     RemoteWebDriver.__init__(
>   File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
>     self.start_session(capabilities, browser_profile)
>   File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
>     response = self.execute(Command.NEW_SESSION, parameters)
>   File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
>     self.error_handler.check_response(response)
>   File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

The content of my Dockerfile:

> FROM python:3
> ADD monitor+log.py /
> ADD requirements.txt /
> RUN apt-get update -y
> RUN apt-get install libnotify-bin -y
> RUN apt-get install espeak -y
> RUN pip3 install -r requirements.txt
> RUN curl -L https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz | tar xz -C /usr/local/bin
> RUN curl -L https://chromedriver.storage.googleapis.com/79.0.3945.36/chromedriver_linux64.zip -o temp.zip ; unzip temp.zip -d /usr/bin
> CMD [ "python3", "./monitor+log.py" ]

Any ideas on how to fix this?

**Comment by BuileaTM** [comment]
Sorry, was missing a few things: Firefox and version alignment of the requirements.

**Comment by BuileaTM** [comment]
Still have stuggles. My error:
"selenium.common.exceptions.WebDriverException: Message: invalid argument: can't kill an exited process"

What version combination of geckodriver and firefox did you used?

**Comment by rizwansoaib** [comment]
> Still have stuggles. My error:
> "selenium.common.exceptions.WebDriverException: Message: invalid argument: can't kill an exited process"
> 
> What version combination of geckodriver and firefox did you used?
geckodriver-v0.26.0
Firefox-v70.0.1
