### ISSUE TITLE
Newest version is heavy in chrome and crashes often.

### ISSUE THREAD

**Issue by dabster3000** [rizwansoaib/whatsapp-monitor#37]
Newest version is heavy in chrome and crashes often. I don't know what data to provide, but after 6-8 hours the tab itself crashes on a reasonable 4 gb system, all other chrome tabs remain ok.

This never used to be the case with previous version.

**Comment by rizwansoaib** [comment]
Array are using to store history maybe if contact had come online often repeatedly and javascript array will be overflow can you confirm with running 6-8 hr normal WhatsApp Users not too much online.
Let me know also Performance of memory using ctrl+shift+c then select right shift then memory.

**Comment by dabster3000** [comment]
What more I can tell more is at times, crashreporter.whatsapp.com starts to be loading on this tab..

**Comment by dabster3000** [comment]
Ok, I shall have that when it crashes next, but I looked at task manager and the chrome started to show 600mb usage with only this Tab.

**Comment by rizwansoaib** [comment]
We are using now can anybody confirm that using API will it take the memory and affect system perfomance.

**Comment by rizwansoaib** [comment]
@dabster3000  First Uninstall Extension note down memory from ctrl+shift+c then memory 
after install extension and start monitorig then note down memory performance of javascript VM .
