### ISSUE TITLE
To Do HTML 

### ISSUE THREAD

**Issue by rizwansoaib** [rizwansoaib/whatsapp-monitor#47]
Make pull requests for  html code for the given wireframe images

You can also suggest for advanced UI/UX looks 

![IMG_20200928_110720](https://user-images.githubusercontent.com/29729380/94394467-0fa4dd00-017b-11eb-8b9d-93dfc86cd878.jpg)

**Comment by rizwansoaib** [comment]
![New Doc 2020-09-29 13 02 03_1](https://user-images.githubusercontent.com/29729380/94527118-2408d880-0254-11eb-8e6d-3427e32e958c.jpg)

**Comment by Baricanac** [comment]
How about adding favorites which will be monitored once you start monitoring by pressing on the OK button without having to add all the phone numbers each time you restart the WhatsAppMonitor application?
