### ISSUE TITLE
Desktop app bug

### ISSUE THREAD

**Issue by BlackDragonWarrior** [rizwansoaib/whatsapp-monitor#57]
The Desktop app version 1.0 was working well untill last month. now it is not working. however version 1.1.0 has bugs. it does not monitor the "Target" instead it monitors random a particular group. I tried reinstalling many times it did not work. My feedback is, you are a genius developer. especially the desktop version 1.0.0 was a King of your work. but surprisingly it is not working currently. by the way i'am a huge fan of yours. I wish to contribute to you but right now i'm not able to but keep your link open please, in a 3-4months I will be making contribution upto my ability. thanks for giving these tools. this is a marvellous tool. God bless you

**Comment by rizwansoaib** [comment]
I will try to improve and bug free in next version
Thank you

**Comment by rizwansoaib** [comment]
In previous version actually Whatsapp is changing backend and class name in html so there is problem not working now .


Please wait for next update version

**Comment by BlackDragonWarrior** [comment]
> In previous version actually Whatsapp is changing backend and class name in html so there is problem not working now .
> 
> Please wait for next update version

I greatly appreciate your work, efforts and your dedication. My suggestion is that please work on version 1.0.0. The app is without bug, stable, highly reliable and accurate. My opinion is that you can start selling these apps as well. Your efforts need to be paid. thank you
