### ISSUE TITLE
From today it's not tracking anything TypeError: Cannot read property 'Presence' of undefined     at <anonymous>:286:34

### ISSUE THREAD

**Issue by GitUserNoor** [rizwansoaib/whatsapp-monitor#67]
**Describe the bug**
Looks like the online/offline tracking is not happening from today . I am seeing TypeError: Cannot read property 'Presence' of undefined
    at <anonymous>:286:34

**To Reproduce**
1. Go to  

**Expected behavior**
How earlier it was showing popup , it is not showing . so it should track the presence and show the popup .
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rizwansoaib** [comment]
is this problem in Desktop or Chrome Extension

**Comment by Sidrti** [comment]
> 
> 
> is this problem in Desktop or Chrome Extension

Still Occuring in Chrome Extension

**Comment by rizwansoaib** [comment]
Create new issue if many people are facing same issue they will also comment

**Comment by rizwansoaib** [comment]
> > is this problem in Desktop or Chrome Extension
> 
> Still Occuring in Chrome Extension

I don't think there should be problem. With presence
