### ISSUE TITLE
windows app isn't working anymore

### ISSUE THREAD

**Issue by tejas9969** [rizwansoaib/whatsapp-monitor#68]
it was working until last night, but since today it doesn't show anything

**Comment by rizwansoaib** [comment]
Please try browser exteinsion untill this problem will not be fixed 
Browser Extension is working fine...

**Comment by tejas9969** [comment]
firefox extension dosent seem to be working as well, will the desktop app be fixed sir?

**Comment by rizwansoaib** [comment]
> firefox extension dosent seem to be working as well, will the desktop app be fixed sir?

https://addons.mozilla.org/en-US/firefox/addon/whatsapp-online-monitor/


remove and reinstall or update version 2.4

**Comment by rizwansoaib** [comment]
Desktop App Updated please reinstall v1.2
