### ISSUE TITLE
Disable notification for all online contacts 

### ISSUE THREAD

**Issue by yuryrodrigues** [rizwansoaib/whatsapp-monitor#75]
Hello!

First, the extension is wonderful. Thank you!

I want only receive notification for contacts who I "Subscribed".

Today I receive notification for all online contacts.

Bellow is a image of a notification for a contact what I not "Subscribed".

Is there any provision to fix this bug?

![image](https://user-images.githubusercontent.com/7195945/114476489-af363400-9bd0-11eb-9a40-0afaa2199283.png)

![image](https://user-images.githubusercontent.com/7195945/114477327-6aab9800-9bd2-11eb-8708-c5ccda34f73b.png)

**Comment by rizwansoaib** [comment]
Hey this not whatsapp monitor icon please check again you have installed another app the logo is different and it's WA Tracker sorry in this open source repo there is not features for subscribe till now but we will add soon .
