### ISSUE TITLE
Whatsapp monitor app not working after an update to Whatsapp web .

### ISSUE THREAD

**Issue by saiviraaj** [rizwansoaib/whatsapp-monitor#85]
There was an update to Whatsapp Web , after the update Whatsapp monitor Chrome extension is not working ( not showing any notification when the contact is online)

Chrome version : 91.0.4472.124  (up to date) 

Please resolve the issue asap.

Thanks

**Comment by sekooo** [comment]
Hi Rizwan, Yes tracker is not working after today whatsapp web update.. Please help

**Comment by alxndrk** [comment]
Hello! I have the same problem! Rizwan please help! Whatsapp Online Monitor 1.2 dosent work(((

**Comment by rizwansoaib** [comment]
sorry i have saw your issue now .

so maybe all users are facing these issue. 
From night after 6 hour i will see issues and bug i hope it will resolve till tomorrow.

i request if you have any console log please upload in this issues that will save my time. 

For debug open console ctrl+shift+c what error is getting?


Thank You

**Comment by rizwansoaib** [comment]
Take all your backup from [Contact Online  History data]( https://whatsappanalysis.in/ ) we are moving new database and login all source code will redefined after 1st August 2021. 
All data will be delete contact online history.

**Comment by clecthiago** [comment]
> There was an update to Whatsapp Web , after the update Whatsapp monitor Chrome extension is not working ( not showing any notification when the contact is online)
> 

Thanks for tell that !
My Chrome version is 91.0.4472.114
I've some problems with logging after some hours so I usually update my Wppweb page (pressing F5) each 12 hours and I was already be prepare for this. Until now.
I dont updated my page and still works for me..

So guys, if possible dont update your page can works

**Comment by rizwansoaib** [comment]
bug is fixing any features you want to add in next updated version...

Your idea are welcome

**Comment by Spipous200** [comment]
> > There was an update to Whatsapp Web , after the update Whatsapp monitor Chrome extension is not working ( not showing any notification when the contact is online)
> 
> Thanks for tell that !
> My Chrome version is 91.0.4472.114
> I've some problems with logging after some hours so I usually update my Wppweb page (pressing F5) each 12 hours and I was already be prepare for this. Until now.
> I dont updated my page and still works for me..
> 
> So guys, if possible dont update your page can works

If u keep all js file of WhatsApp Will be great like this we can know wich file cause the bug

**Comment by Colovod** [comment]
When I open browser console in Firefox, I see there an error.

```
TypeError: window.Store is undefined
<anonymous> https://web.whatsapp.com/:286
setInterval handler* https://web.whatsapp.com/:223
```

Every single second this error occures in the console. Is there a fix for it?

**Comment by rizwansoaib** [comment]
Bug fix please reinstall new version and test and verify it...

**Comment by Colovod** [comment]
Thank you for the quick fix! I installed new version 2.5 and it works now! Thank you very much!

**Comment by alxndrk** [comment]
> Bug fix please reinstall new version and test and verify it...

What about desktop version?

**Comment by rizwansoaib** [comment]
Desktop Version will be tomorrow or tonight...

**Comment by sekooo** [comment]
@rizwansoaib  Thank you,  we are waiting you :)

**Comment by rizwansoaib** [comment]
@sekooo check updated desktop version...
