### ISSUE TITLE
Track for Contact list start only if open chat

### ISSUE THREAD

**Issue by Spipous200** [rizwansoaib/whatsapp-monitor#90]
In this update the tracking for Contact that i have conversatiom with them start only if i open the chat conversation once  befor was tracking automáticly  the Contact in chat list withouth open the chat once

**Comment by rizwansoaib** [comment]
You have to open chat atleast once either from phone or whatsapp web.
its from whatsapp end.

**Comment by rizwansoaib** [comment]
v2.6 add favourite contacts and it will open automatically chat in startup extension...

**Comment by Spipous200** [comment]
Thanknyou rawzan for fast fixing bug and cominication
